version: '3'
services:

  member_mgmt:
    image: mysql:5.7-debian
    platform: linux/amd64
    ports:
      - "9992:3306"
    expose:
      - "9992"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: sample
    volumes:
      - "./sqls/:/docker-entrypoint-initdb.d/"
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci